#pragma config(Sensor, S1,     touch,          sensorTouch)
#pragma config(Sensor, S2,     sonar,          sensorSONAR)
#pragma config(Sensor, S4,     light,          sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	/** MAKES	 STRIDER	GO	BACKWARDS
	motor[motorA] = 20;
	motor[motorB] = -20;
	motor[motorC] = 20;
	**/

	/** MAKES	 STRIDER	GO	FORWARDS
	motor[motorA] = -20;
	motor[motorB] = 20;
	motor[motorC] = -20;
	**/

	nMotorEncoder[motorA] = 0;
	nMotorEncoder[motorB] = 0;
	nMotorEncoder[motorB] = 0;

	// sync motors
	nSyncedMotors = synchAB;
	nSyncedMotors = synchAC;

	// motor encoder
	/**
	int encPerCM = 360/(2*PI*(1));

	int target_encoder = encPerCM * 20; // travel 20 cm first

	while(nMotorEncoder[motorA] <= target_encoder ||
	nMotorEncoder[motorB] <= target_encoder ||
	nMotorEncoder[motorC] <= target_encoder){ // go forward 20cm

	motor[motorA] = -20;
	motor[motorB] = 20;
	motor[motorC] = -20;
	}
	**/

	// calculate threshold
	int threshold = (53 + 69) / 2;
	displayTextLine(2, "threshold: %4d", threshold);

	while(true){ // then walk forward until its within 20 cm of object, then turn around

		if(SensorValue[sonar] > 20){
			// forwards
			motor[motorA] = -50;
			motor[motorB] = 50;
			motor[motorC] = -50;

			// line tracing
			if(SensorValue(light) < threshold ){ // on brown

				motor[motorA] = -30;
				motor[motorB] = 30;
				motor[motorC] = -30;

				// print the value that it sees
				displayTextLine(1, "Name				Value");
				displayTextLine(4, "Light Value: %4d", SensorValue(light));

				}else{// on white
				// turn and go forward
				// make it turn
				motor[motorA] = 0;
				motor[motorB] = 30;
				motor[motorC] = -70;

				wait1Msec(20000);

				// forwards
				motor[motorA] = -50;
				motor[motorB] = 50;
				motor[motorC] = -50;

				// play sound
				playSound(soundBeepBeep);
				// print the value that it sees
				displayTextLine(4, "Light Value: %4d", SensorValue(light));

			}


			}else{
			// backwards
			motor[motorA] = 50;
			motor[motorB] = -50;
			motor[motorC] = 50;

		}

		if(SensorValue[touch] == 1){ // is pressed

			// walk backwards
			motor[motorA] = -50;
			motor[motorB] = 50;
			motor[motorC] = -50;
			wait1Msec(3000);

		}

		// line tracing
		if(SensorValue(light) < threshold ){ // on brown

			motor[motorA] = -30;
			motor[motorB] = 30;
			motor[motorC] = -30;

			// print the value that it sees
			displayTextLine(4, "Light Value: %4d", SensorValue(light));

			}else{// on white
			// turn and go forward
			// make it turn
			motor[motorA] = 0;
			motor[motorB] = 30;
			motor[motorC] = -70;

			wait1Msec(20000);

			// forwards
			motor[motorA] = -50;
			motor[motorB] = 50;
			motor[motorC] = -50;

			// play sound
			playSound(soundBeepBeep);
			// print the value that it sees
			displayTextLine(4, "Light Value: %4d", SensorValue(light));

		}

	}


}
